### ISSUE TITLE
Can't Save edited images

### ISSUE THREAD

**Issue by ThisaraMalintha** [FSchiltz/RawParser#13]
When I tap save fast ink app opens

I'm on a Windows 10 mobile creators update build

**Comment by FSchiltz** [comment]
Hi, what is fast ink ? I'll look into it this week

**Comment by ThisaraMalintha** [comment]
It’s an inking app.
https://www.microsoft.com/en-us/store/p/fast-ink/9nblggh52t6c

I’ve uninstalled it and now I can save edited images without a problem. I think this problem is only happens in creators update build previously I used both apps in anniversary update production ring without a problem.

Anyway You are doing great job with raw image editor man. Good Luck and keep up the good work.
