### ISSUE TITLE
Panasonic RW2 support

### ISSUE THREAD

**Issue by cazcam2000** [FSchiltz/RawParser#15]
Panasonic camera's use RW2 raw images, is there any support for this?

**Comment by FSchiltz** [comment]
I'll look into it as soon as I start the development again. (it's just a quick fix in the RW parser)

**Comment by FSchiltz** [comment]
Hello, I've started development again and I've fix a big bug in the RW2 decoder (it display an image but the color are still a bit off) so in a few days I can fix it

**Comment by FSchiltz** [comment]
Done, but it may not work with all the panasonic camera
